# r1 = range(7)
# print (*r1)
# r12 = range(100, 106)
# print (*r12)
# r13 = range(9, 1, -1)
# print (*r13)
a = int(input("give a number:"))
b = int(input("give another number:"))
r = range (a, b)
print (*r)